name: Build and Test

on: push

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install MySQL 
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo -E apt-get update
          sudo -E apt-get -q -y install mysql-server
          sudo systemctl start mysql
          sudo mysql -u root -proot -e "SELECT User,Host FROM mysql.user;
                                        DROP USER 'root'@'localhost';
                                        CREATE USER 'root'@'%' IDENTIFIED BY '';
                                        GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
                                        FLUSH PRIVILEGES;"

      - name: Install Java 8
        uses: actions/setup-java@v1
        with:
          java-version: '8.0.x'

      # cache conda packages to speedup
      - name: Cache conda
        uses: actions/cache@v1
        env:
          CACHE_NUMBER: 1
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('script/install/conda_eva_environment.yml') }}

      - name: Install conda packages
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: eva
          channel-priority: strict
          environment-file: script/install/conda_eva_environment.yml
          use-only-tar-bz2: true

      - name: Generate eva-ql parser
        run: sh script/antlr4/generate_parser.sh

      - name: Test
        shell: bash
        run: |
          eval "$(conda shell.bash hook)"
          conda activate eva
          conda info
          sh script/test/test.sh
